import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NotePage from "components/notes/NotePage";
import { Navbar, Container } from "react-bootstrap";

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar fixed="top" expand="lg" variant="light" bg="light">
        <Container>
          <Navbar.Brand href="#">Welcome to your Notepad!</Navbar.Brand>
        </Container>
      </Navbar>

      <Head>
        <title>Notepad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NotePage />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
