import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NotePage from "components/notes/NotePage";
import { Navbar, Container } from "react-bootstrap";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notepad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar fixed="top" expand="lg" variant="light" bg="light">
        <Container>
          <Navbar.Brand href="#">Welcome to your Notepad!</Navbar.Brand>
        </Container>
      </Navbar>

      <main className={styles.main}>
        <NotePage />
      </main>

      <footer className={styles.footer}>
    
      </footer>
    </div>
  );
}
